ARG BAZEL_OPTS="--config=release_gpu_linux --action_env=TENSORRT_INSTALL_PATH=/usr"
ARG CC_OPT_FLAGS=""

ARG CUDA=11.0
ARG CUDA_VERSION 11.0.3
ARG CUDNN=8.0.5.39-1
ARG CUDNN_MAJOR_VERSION=8
ARG LIB_DIR_PREFIX=x86_64
ARG LIBNVINFER=7.1.3-1
ARG LIBNVINFER_MAJOR_VERSION=7
ARG TF_CUDA_COMPUTE_CAPABILITIES=3.5,7.5,8.6
ARG TF_CUDA_VERSION=11
ARG TF_TENSORRT_VERSION=7
