ARG TARGETARCH=${TARGETARCH:-amd64}
ARG BAZEL_OPTS_AMD64="--config=release_gpu_linux"
ARG CC_OPT_FLAGS_AMD64=""

ARG CUDA=11.2
ARG CUDA_VERSION 11.2.2
ARG CUDNN=8.1.0.77-1
ARG CUDNN_MAJOR_VERSION=8
ARG LIB_DIR_PREFIX=x86_64
ARG LIBNVINFER=7.2.2-1
ARG LIBNVINFER_MAJOR_VERSION=7
ARG TF_CUDA_COMPUTE_CAPABILITIES=3.5,7.5,8.6
ARG TF_CUDA_VERSION=11
ARG TF_TENSORRT_VERSION=7

# note: this libnvinfer uses cuda11.1 versions 
ARG LIBNVINFER_CUDA=11.1
