ARG DEVTOOLSET="7,8"
ARG GOLANG_VERS="1.19"
ARG USE_BAZEL_VERS="3.7.2"
ARG PROTOBUF_VERS="3.17.3"
ARG TENSORFLOW_VERS="2.6.5"
ARG TENSORFLOW_VERS_SUFFIX=""
ARG TF_GIT_TAG=${TENSORFLOW_VERS:+v${TENSORFLOW_VERS}${TENSORFLOW_VERS_SUFFIX}}
ARG TF_GO_VERS=${TENSORFLOW_VERS:+v${TENSORFLOW_VERS}+incompatible}
