ARG GOLANG_VERS="1.17"
ARG USE_BAZEL_VERS="3.7.2"
ARG PROTOBUF_VERS="3.19.1"
ARG TENSORFLOW_VERS="2.7.0"
ARG TENSORFLOW_VERS_SUFFIX=""
ARG TF_GIT_TAG=${TENSORFLOW_VERS:+v${TENSORFLOW_VERS}${TENSORFLOW_VERS_SUFFIX}}
ARG TF_GO_VERS=${TENSORFLOW_VERS:+v${TENSORFLOW_VERS}+incompatible}
