ARG DEVTOOLSET="7,9"
ARG GOLANG_VERS="1.19"
ARG USE_BAZEL_VERS="5.0.0"
ARG PROTOBUF_VERS="3.20.1"
ARG TENSORFLOW_VERS="2.9.1"
ARG TENSORFLOW_VERS_SUFFIX=""
ARG TF_GIT_TAG=${TENSORFLOW_VERS:+v${TENSORFLOW_VERS}${TENSORFLOW_VERS_SUFFIX}}
ARG TF_GO_VERS=${TENSORFLOW_VERS:+v${TENSORFLOW_VERS}+incompatible}
